# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plenti < Formula
  desc "Dead simple SSG with Svelte frontend and Go CLI."
  homepage "https://plenti.co/"
  version "0.6.24"

  on_macos do
    url "https://github.com/plentico/plenti/releases/download/v0.6.24/plenti_ v0.6.24_mac_all.tar.gz"
    sha256 "f383ba4101136f8eb936cb245d5076c7980197bcfe9976c6839b94447fe48ace"

    def install
      bin.install "plenti"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/plentico/plenti/releases/download/v0.6.24/plenti_ v0.6.24_linux_64-bit.tar.gz"
      sha256 "793ab3e664117f86292147916e595d3f686c6abdc79a76d7cdac30033083f452"

      def install
        bin.install "plenti"
      end
    end
  end
end
