# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plenti < Formula
  desc "Dead simple SSG with Svelte frontend and Go CLI."
  homepage "https://plenti.co/"
  version "0.6.26"

  on_macos do
    url "https://github.com/plentico/plenti/releases/download/v0.6.26/plenti_mac_64-bit.tar.gz"
    sha256 "6a8c954e89207d9ce49793e7f353cad581cd7fe579223c9b0fb6b706050684fe"

    def install
      bin.install "plenti"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/plentico/plenti/releases/download/v0.6.26/plenti_linux_64-bit.tar.gz"
      sha256 "f3320e96b63cd6b7afa0c0c558baa37035b51b37e2d7c6c4cb4fbe648a85db46"

      def install
        bin.install "plenti"
      end
    end
  end
end
