# This file was generated by GoReleaser. DO NOT EDIT.
cask "plenti" do
  desc "Dead simple SSG with Svelte frontend and Go CLI."
  homepage "https://plenti.co/"
  version "0.7.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plenti"

  on_macos do
    url "https://github.com/plentico/plenti/releases/download/v0.7.25/plenti_0.7.25_mac_64-bit.tar.gz"
    sha256 "75b30f5c3d919604d93f3b867576ae6a648c2e25e3b2acd863928a8bfad7e166"
  end

  on_linux do
    on_intel do
      url "https://github.com/plentico/plenti/releases/download/v0.7.25/plenti_0.7.25_linux_64-bit.tar.gz"
      sha256 "d101bab55e2f18cfd22e43dd0e138755749266625bfd503ced2c8e88d06c564a"
    end
  end

  # No zap stanza required
end
